[build]
  base = "server/client"
  command = "rm -f yarn.lock && npm install && npm run build"
  publish = "dist"
  functions = "../netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions configuration
[functions]
  directory = "../netlify/functions"
